### ISSUE TITLE
k8s cluster 별 노드 현황 집계 기능 추가

### ISSUE THREAD

**Issue by kilsoo75** [cnpst/zcp-admin-cluster#2]
ZMP 에 등록되어 있는 cluster 의 api-server token 을 통해서 노드 정보를 취합하는 batch 개발.
ZCP cluster 관리 화면 추가 내용
1. 리스트 화면에서 management/logging/worker/zdb 노드 수 현황 표시
2. cluster 디테일 화면에서 각 노드의 디테일 정보 확인

**Comment by kbtapjm** [comment]
- Prometheus Pushgateway
https://github.com/prometheus/pushgateway

**Comment by kbtapjm** [comment]
Pushgateway를 사용하는 경우
- 스크랩 할 수없는 구성 요소를 모니터링해야 할 경우

Pushgateway를 사용해야 하는지? (유의점)
- 단일 Pushgateway를 통해 여러 인스턴스를 모니터링 할 때 Pushgateway는 단일 장애 지점이되고 병목 현상이 발생
- 업 메트릭 (모든 스크랩에서 생성됨)을 통해 Prometheus의 자동 인스턴스 상태 모니터링을 잃게 됨
- Pushgateway는 푸시 된 시리즈를 잊지 않으며 해당 시리즈가 Pushgateway의 API를 통해 수동으로 삭제되지 않는 한 영원히 Prometheus에 노출 됨

**Comment by kbtapjm** [comment]
#### 요구사항은?
- Cluster의 Node 정보를 조회하기 위함
- Cluster의 Node 상태를 모니터링 하기 위해서

#### 어떻게 해야 하는가?
- Cluster api-server를 호출해서 Node 정보를 가져와야 됨
- api-server를 접근하기 위해서는 api-server url 정보와 token 정보가 필요함

#### Cluster Node 집계 배치
- 조건 : Cluster 의 Status가 `Running` 인 상태
- 주기 : 30초마다 요청

**Comment by kbtapjm** [comment]
- Nodes
https://kubernetes.io/docs/concepts/architecture/nodes/

**Comment by kilsoo75** [comment]
EKS ==> eks.amazonaws.com/nodegroup=zcp-4-16
IKS ==> ibm-cloud.kubernetes.io/worker-pool-name=zcp_4_16_shared
AKS ==> TBD

**Comment by kbtapjm** [comment]
2020-05-22 리뷰
- 필터 조건에 Name, CSP, Roles, Status 추가
- 자동 리프레쉬 기능 삭제
